### ISSUE TITLE
Enhancement: Report signal strength and C/N ratio 

### ISSUE THREAD

**Issue by allanlatham** [mighty-p/t2scan#3]
In many areas the same service can be received on different frequencies. This results in a channels.conf which contains (almost) duplicate entries. It would be good to know the quality of the reception on each frequency in order to decide which duplicate entries to discard.

If it is possible without detracting from the simplicity of the program please add an optional extra scan of those transponders on which were found usable signals. During this scan measure and report the signal strength and C/R ratio.

**Comment by mighty-p** [comment]
At the moment, you can mark these duplicates (in vdr output only) with "-d". Then you can select yourself, which of the instances you want to copy and paste to your channels.conf.

I have actually tried around with measuring signal strength and quality and even have code for that here. However, in my tests (another user in vdrportal helped me), it turned out that the values given back by the dvb-t card drivers don't seem to be very meaningful to make an automatic choice. Therefore, I removed the code again from GIT. I can think about adding it and using it in the comment lines that "-d" produces to mark the channels. I will think about that.

**Comment by mighty-p** [comment]
Ok, I decided to add the signal measuring code again and the measured strength and CNR will then be added to the channel list as comments. A code push will follow as soon as I have the code fully ready.

**Comment by mighty-p** [comment]
This is now fully implemented in commit 8c01eef833a380112099762a6ab5f884ca2091ae (parameters -d and -r).
