### ISSUE TITLE
No support for German special characters

### ISSUE THREAD

**Issue by andimik** [mighty-p/t2scan#8]
In Austria, public broadcaster ORF uses German Umlauts for some channels. When scanning such a mux, this error appears:

```
WARNING: 		char_coding 223: iconv failed.
		Invalid or incomplete multibyte or wide character
	service = Radio sterreich 1 (ORF)
WARNING: 		char_coding 223: iconv failed.
		Invalid or incomplete multibyte or wide character
	service = Hitradio 3 (ORF)
	service = radio FM4 (ORF)
WARNING: 		char_coding 223: iconv failed.
		Invalid or incomplete multibyte or wide character
	service = 3-Visual-Radio (ORF)
```

The services are called

> Ö3-Visual-Radio
> Hitradio Ö3
> Radio Österreich 1

The output missed the special characters:

```
Radio sterreich 1;ORF:498000:B8D0S1Y0P1:T:27500:0:0;4090:0:0:14409:8232:401:0
Hitradio 3;ORF:498000:B8D0S1Y0P1:T:27500:0:0;4130:0:0:14413:8232:401:0
radio FM4;ORF:498000:B8D0S1Y0P1:T:27500:0:0;4140:0:0:14414:8232:401:0
3-Visual-Radio;ORF:498000:B8D0S1Y0P1:T:27500:4150=27:0;4130:0:0:14415:8232:401:0
```

**Comment by mighty-p** [comment]
Hi @andimik ,

I checked and an on my system, I have no issues with umlauts. However, I don't receive Austrian DVB-T. For the German DVB-T2, for example the services "BR Fernsehen Süd HD" and "WDR HD Köln" are correctly detected for me.

Therefore, I suspect that the problem is either that the service names broadcast by ORF are in a different charset as expected by t2scan or the problem has to do with the charset used by your system. Maybe as a starting point, can you let me know the output of "echo $LANG"? E.g., for me it returns "de_DE.UTF-8".
It may also be worth trying if using the parameter -I (see -H for an explanation) does help here.

**Comment by andimik** [comment]
I've never faced problems in Windows, using TS Reader, DVB Viewer and Transedit for lots of years now.

```
$ echo $LANG
de_DE.UTF-8
```
German OS, too, it's Ubuntu 20.04 Mate.

`$ t2scan -t 2 -l 24 -p 1 -I UTF-8`, 
`$ t2scan -t 2 -l 24 -p 1 -I ISO-8859-15` and 
`$ t2scan -t 2 -l 24 -p 1 -I ISO-8859-1` 
all result in the same output, see textfile attached (remark: I'm using a SONY chipset, where there are no PLPs, so don't be shocked, it's PLP 1, indeed)
[t2scan_output.txt](https://github.com/mighty-p/t2scan/files/4636764/t2scan_output.txt)
 
Can you see it in the TS-Reader output, for instance http://andimik.bplaced.net/dvbt/aut_muxa_stbk_20190501.htm ?

I tried VLC, here the chars are wrong, too.

![grafik](https://user-images.githubusercontent.com/24510556/82088463-17934180-96f2-11ea-8487-911251095a07.png)

How could I support you for finding that out? Seems t2scan uses a stick as input and cannot scan a ts-file.

**Comment by mighty-p** [comment]
Actually, the log with the hex dump of the service descriptors is indeed helpful. From this I can see that the channel names (for example "Radio Österreich 1") are iso8859-1 encoded. However, it seems for some reasons t2scan thinks it's utf-8 and tries to process it like utf-8. I need to dig a bit deeper to understand why this is the case, but I am actually optimistic that I can fix this.

**Comment by andimik** [comment]
Seems 0xD6 gets lost.

**Comment by mighty-p** [comment]
Yes, t2scan thinks that 0xD6 is the first of a two-byte UTF-8 character while it's actually the one-byte iso8859-1 character "Ö".

**Comment by andimik** [comment]
I've attached the log with `t2scan -t 2 -l 24 -p 1 -v -v -v -I ISO-8859-1`

[t2scan_ISO-8859-1.txt](https://github.com/mighty-p/t2scan/files/4638131/t2scan_ISO-8859-1.txt)

**Comment by mighty-p** [comment]
Hi @andimik , can you please run another scan with the latest GIT and "-v -v -v"? I added two additional debug messages to verify that the problem is that a wrong charset is assumed.

Btw, probably the "-I" parameter won't help here since it just changes the destination charset and not the one assumed to be used in the SDT.

**Comment by andimik** [comment]
I hope this is the correct one as you seem not to update the version.

```
$ t2scan -V
t2scan -V 
20200501
```

[t2scan_test.txt](https://github.com/mighty-p/t2scan/files/4639184/t2scan_test.txt)

**Comment by mighty-p** [comment]
Thanks. Yes, I am not updating the version string with every commit. But the debug message that I added is in your output. I am checking now if it helps as much as I hope.

**Comment by mighty-p** [comment]
@andimik Can you kindly update to latest GIT and create the same log once more. I think we are close to getting this fixed but I want to double check one more thing.

**Comment by andimik** [comment]
Here you are

[t2scan.txt](https://github.com/mighty-p/t2scan/files/4639257/t2scan.txt)

```
$ git show
commit f590a24040d56a953eb0c779277fe86c4211ab85 (HEAD -> master, origin/master, origin/HEAD)
Author: mighty-p <mighty-p@example.com>
Date:   Sat May 16 22:51:28 2020 +0200

```

**Comment by mighty-p** [comment]
Thanks.

Root cause of the issue is now clear. ORF does not specify an encoding for their strings (the first byte of the text field is in the range of 0x20 to 0xFF. According to [EN 300 468](https://www.etsi.org/deliver/etsi_en/300400_300499/300468/01.11.01_60/en_300468v011101p.pdf) this means that ISO6937-2 should be assumed (with a modification for the Euro sign) - which is what t2scan does. Seems that actually ORF uses ISO8859-15 instead.

Can you please try to apply the following patch:
```
--- char-coding.c.orig	2020-05-16 23:48:02.547916814 +0200
+++ char-coding.c	2020-05-16 23:49:22.330883199 +0200
@@ -159,9 +159,10 @@
   if (dvb_charset_id > iconv_codes_count()) {
      // no special character coding applied: use iso6937-2 w. euro add-on
      char * pEuro;
-     DVBCHARSET("ISO69372");
+//     DVBCHARSET("ISO69372");
+     DVBCHARSET("ISO885915");
 
-     while (**inbuf && (pEuro = strchr(*inbuf, 0xA4))) {
+     while (0 && **inbuf && (pEuro = strchr(*inbuf, 0xA4))) {
            // handle the euro add-on
            char * ebuf = calloc(3,1);
            char * pi = ebuf;
```

I like to see if it fixes the problem. I am a bit reluctant to just do these changes and commit them since this is definitely against the standard and may break the correct string recognition of providers correctly implement the standard.

**Comment by andimik** [comment]
Very interesting. Will test it in the morning.

**Comment by andimik** [comment]
The patch itself does not work.

```
$ git apply --check /tmp/t2scan.patch
error: Anwendung des Patches fehlgeschlagen: char-coding.c:159
error: char-coding.c: Patch konnte nicht angewendet werden
```
so I had to edit the two lines by myself.

Now the Ö is displayed.

```
Radio Österreich 1;ORF:498000:B8D0S1Y0P1:T:27500:0:0;4090:0:0:14409:8232:401:0
Hitradio Ö3;ORF:498000:B8D0S1Y0P1:T:27500:0:0;4130:0:0:14413:8232:401:0
radio FM4;ORF:498000:B8D0S1Y0P1:T:27500:0:0;4140:0:0:14414:8232:401:0
Ö3-Visual-Radio;ORF:498000:B8D0S1Y0P1:T:27500:4150=27:0;4130:0:0:14415:8232:401:0
```

full output:
[t2scan_after_patch.txt](https://github.com/mighty-p/t2scan/files/4639802/t2scan_after_patch.txt)

I'll report it to the provider ORS.

Attached please find the transport stream without audio/video/data/teletext. Seems EIT is UTF-8 as this is displayed correctly in all tools.
[ORS_mux_a_2020-05-17_09-15-44_basic.zip](https://github.com/mighty-p/t2scan/files/4639815/ORS_mux_a_2020-05-17_09-15-44_basic.zip)

**Comment by mighty-p** [comment]
Thank you.
The funny thing is that actually t2scan also must have a bug since if applying ISO-6937 the converted string should have been "Radio ¬sterreich 1" (as in your screenshot of VLC, so VLC does it correctly).

I believe iconv does not know "ISO69372", but probably knows "ISO6937". 

If you have 2  minutes, can you please try changing the line with "DVBCHARSET("ISO69372");" into "DVBCHARSET("ISO6937");" and let me know if it shows then also the "Radio ¬sterreich 1" string? Then I could fix this as well.

And back to the problem with ORF, I could either introduce a special handling if the provider is "ORF" and then default to ISO-8859-15 or I add an additional parameter for setting the default charset. I need to think an hour or so about this, but please also let me know what you think.

**Comment by andimik** [comment]
Yes, with ISO6937 I get the same character like in VLC:

```
Radio ¬sterreich 1;ORF:498000:B8D0S1Y0P1:T:27500:0:0;4090:0:0:14409:8232:401:0
Hitradio ¬3;ORF:498000:B8D0S1Y0P1:T:27500:0:0;4130:0:0:14413:8232:401:0
radio FM4;ORF:498000:B8D0S1Y0P1:T:27500:0:0;4140:0:0:14414:8232:401:0
¬3-Visual-Radio;ORF:498000:B8D0S1Y0P1:T:27500:4150=27:0;4130:0:0:14415:8232:401:0
```

I guess the first idea (if provider=ORF -> than) is better, although this is just a workaround.

Remark: On Astra, lots of channels use "Austria" instead of "Österreich" in their name :-) but on DVB-T2 this is not even mentioned in the ID.

This is the list for all nationwide terrestrial channels (there are local muxes as well). The field provider is not maintained in Austria and has useless entries (ORF cannot be the provider for private or foreign stations ...)

```
ATV HD;ATV:490000:B8D0G32S1T8Y0P1:T:27500:5010=27:0;5011:5015:69C:14501:8232:501:0
PULS 4;sevenonemedia:490000:B8D0G32S1T8Y0P1:T:27500:5020=27:0;5021:5025:69C:14502:8232:501:0
ServusTV HD;ServusTV:490000:B8D0G32S1T8Y0P1:T:27500:5030=27:0;5031,5032:5035:69C:14503:8232:501:0
RTL HD;RTL:490000:B8D0G32S1T8Y0P1:T:27500:5040=27:0;5041:5045:69C:14504:8232:501:0
3sat HD;3SAT:490000:B8D0G32S1T8Y0P1:T:27500:5050=27:0;5051,5052:5055:69C:14505:8232:501:0
ZDFinfo;ORS:490000:B8D0G32S1T8Y0P1:T:27500:5060=27:0;5061:5065:69C:14506:8232:501:0
HGTV;-:490000:B8D0G32S1T8Y0P1:T:27500:5070=27:0;5071:0:69C:14507:8232:501:0
ATV 2;ATV:490000:B8D0G32S1T8Y0P1:T:27500:5080=27:0;5081:5085:0:14508:8232:501:0
Flimmit Zusatzpaket;ORS:490000:B8D0G32S1T8Y0P1:T:27500:5090=27:0:0:0:14509:8232:501:0
ORF1 HD;ORF:498000:B8D0S1Y0P1:T:27500:4010=27:0;4011,4012:4015:69C:14401:8232:401:0
ORF2 T HD;ORF:498000:B8D0S1Y0P1:T:27500:4000=27:0;4001,4002:4005:69C:14402:8232:401:0
ORF2 V HD;ORF:498000:B8D0S1Y0P1:T:27500:4000=27:0;4001,4002:4005:69C:14403:8232:401:0
ORF2 K HD;ORF:498000:B8D0S1Y0P1:T:27500:4000=27:0;4001,4002:4005:69C:14404:8232:401:0
ORF III HD;ORF:498000:B8D0S1Y0P1:T:27500:4050=27:0;4051,4052:4055:69C:14405:8232:401:0
ORF Sport+ HD;ORF:498000:B8D0S1Y0P1:T:27500:4060=27:0;4061,4062:4065:69C:14406:8232:401:0
ORF1;ORF:498000:B8D0S1Y0P1:T:27500:4070=27:0;4071:4015:0:14407:8232:401:0
ORF2 W;ORF:498000:B8D0S1Y0P1:T:27500:4080=27:0;4081:4005:0:14408:8232:401:0
Radio ¬sterreich 1;ORF:498000:B8D0S1Y0P1:T:27500:0:0;4090:0:0:14409:8232:401:0
Hitradio ¬3;ORF:498000:B8D0S1Y0P1:T:27500:0:0;4130:0:0:14413:8232:401:0
radio FM4;ORF:498000:B8D0S1Y0P1:T:27500:0:0;4140:0:0:14414:8232:401:0
¬3-Visual-Radio;ORF:498000:B8D0S1Y0P1:T:27500:4150=27:0;4130:0:0:14415:8232:401:0
ZDF HD;ORF:546000:B8D0G16S1T32Y0P1:T:27500:7010=27:0;7011,7012:7015:69C:14701:8232:701:0
Das Erste HD;ORF:546000:B8D0G16S1T32Y0P1:T:27500:7020=27:0;7021,7022:7025:69C:14702:8232:701:0
ZDFneo HD;ORF:546000:B8D0G16S1T32Y0P1:T:27500:7030=27:0;7031,7032:7035:69C:14703:8232:701:0
Eurosport 1;ORF:546000:B8D0G16S1T32Y0P1:T:27500:7040=27:0;7041:7045:69C:14704:8232:701:0
Sport 1;ORF:546000:B8D0G16S1T32Y0P1:T:27500:7050=27:0;7051:7055:69C:14705:8232:701:0
kabel eins;ORF:546000:B8D0G16S1T32Y0P1:T:27500:7060=27:0;7061:7065:69C:14706:8232:701:0
RTL II;ORF:546000:B8D0G16S1T32Y0P1:T:27500:7070=27:0;7071:7075:69C:14707:8232:701:0
sixx;ORF:546000:B8D0G16S1T32Y0P1:T:27500:7080=27:0;7081:7085:69C:14708:8232:701:0
Playboy TV;ORF:546000:B8D0G16S1T32Y0P1:T:27500:7090=27:0;7091:0:69C:14709:8232:701:0
KiKA;ORF:546000:B8D0G16S1T32Y0P1:T:27500:7100=27:0;7101:7105:69C:14710:8232:701:0
ProSieben HD;ORF:554000:B8D0G16S1T32Y0P1:T:27500:8010=27:0;8011:8015:69C:14801:8232:801:0
PULS 4 HD;ORF:554000:B8D0G16S1T32Y0P1:T:27500:8020=27:0;8021:8025:69C:14802:8232:801:0
SAT.1 HD;ORF:554000:B8D0G16S1T32Y0P1:T:27500:8030=27:0;8031:8035:69C:14803:8232:801:0
VOX HD;ORF:554000:B8D0G16S1T32Y0P1:T:27500:8040=27:0;8041:8045:69C:14804:8232:801:0
PULS 24;ORF:554000:B8D0G16S1T32Y0P1:T:27500:8050=27:0;8051:0:69C:14805:8232:801:0
4MEDIATHEK;ORS:554000:B8D0G16S1T32Y0P1:T:27500:8060=27:0:0:0:14806:8232:801:0
Disney Channel;ORF:554000:B8D0G16S1T32Y0P1:T:27500:8070=27:0;8071:8075:69C:14807:8232:801:0
Deluxe Music;ORF:554000:B8D0G16S1T32Y0P1:T:27500:8080=27:0;8081:0:69C:14808:8232:801:0
CNN ;ORF:554000:B8D0G16S1T32Y0P1:T:27500:8090=27:0;8091:0:69C:14809:8232:801:0
NDR;ORS:554000:B8D0G16S1T32Y0P1:T:27500:8100=27:0;8101:8105:69C:14810:8232:801:0
Radio Maria;ORF:554000:B8D0G16S1T32Y0P1:T:27500:0:0;8111:0:0:14811:8232:801:0
```

**Comment by mighty-p** [comment]
Thanks. That's what I assumed and latest commit actually makes t2scan behave like this. So this issue with ORF helped me to find & fix actually a bug in t2scan :)
Now I need to think how to gracefully handle ORF using ISO8859-15. I believe adding a parameter "-i" (so that you could call it with "-i iso-8859-15") could be a workaround. For country AT I could let it then default to that setting. Let me think a bit about it and maybe I can implement it later today.

**Comment by mighty-p** [comment]
Or I do the special handling for provider "ORF". It's still also an option; I have to think about it.

**Comment by mighty-p** [comment]
Commit b9416d9 hopefully fixes this issue finally. It adds a special handling for ORF provider to assume ISO8859-15 as default encoding. It also adds a new parameter -i to overwrite the default charset encoding (for non-ORF use cases).

**Comment by andimik** [comment]
Yes, this helped. See attachment.

[t2scan_fixed_orf.txt](https://github.com/mighty-p/t2scan/files/4642505/t2scan_fixed_orf.txt)

**Comment by mighty-p** [comment]
Hi,

thanks for confirming that the normal output works now.

Technically, the special characters when using VLC output is a bit different. For VLC output, t2scan uses iso-8859-1 output (as you can see by the line "output charset 'ISO-8859-1'") which creates these invalid characters on an utf-8 system in the debug output. I will open a new issue for that problem and have a look later today if this somehow can be done in a better way.
